"use client";

export const languageNames: { label: string; value: LanguageKey }[] = [
    { label: "browser-default", value: "browser" },
    { label: "English", value: "en" },
    { label: "中文", value: "zh" },
    { label: "Español", value: "es" },
    { label: "Français", value: "fr" },
]

export const languages = {
    browser: {},
    en: {
        "username-is-required": "Username is required",
        "username-format": "Can only contain numbers and uppercase and lowercase letters",
        "password-min-length": "Password must be at least 6 characters",
        "form-validation": "Form validation failed",
        "login-title": "Login to your account",
        "login-subtitle": "Enter your username below to login to your account",
        "username": "Username",
        "username-enter": "Enter your username",
        "password": "Password",
        "login": "Login",
        "google-CAPTCHA": "Google CAPTCHA",
        "google-CAPTCHA-enter": "Not bound, do not fill in",
        "name-is-required": "Name is required",
        "select-area-code": "Please select area code",
        "enter-phone-number": "Please enter your phone number",
        "select-min": "You have to select at least one item.",
        "fail": "Fail",
        "update": "Update",
        "delete": "Delete",
        "query": "Query",
        "add-new": "Add New",
        "admin": "Admin",
        "email": "Email",
        "tele": "Tele",
        "address": "Address",
        "actions": "Actions",
        "avatar": "Avatar",
        "name": "Name",
        "enter-name": "Enter name",
        "enter-email": "Enter Email",
        "enter-address": "Enter address",
        "no-modify": "No need to modify",
        "role-list": "Role List",
        "save": "Save",
        "cancel": "Cancel",
        "verify-email": "Please enter a valid email address",
        "submit": "Submit",
        "switch-role-title": "Click the button to switch roles.",
        "current-role": "Current role",
        "super-admin": "Super Administrator",
        "administrator": "Administrator",
        "super-admin-tip": "Super Administrator Function...",
        "permission-list": "Permission List",
        "edit-role": "Edit Role",
        "satisfied": "satisfied",
        "neutral": "Neutral",
        "dissatisfied": "Dissatisfied",
        "customer-satisfaction": "Customer satisfaction",
        "customer-satisfaction-analysis": "Customer satisfaction analysis",
        "product-quality": "Product quality",
        "serve": "Serve",
        "logistics": "Logistics",
        "after-sales": "After-sales",
        "recommend": "Recommend",
        "score": "Score",
        "market-share": "Market share",
        "sales-revenue": "Sales Revenue",
        "order-count": "Order Count",
        "customer-count": "Customer Count",
        "average-order-value": "Average order value",
        "competitor": "Competitor",
        "own": "Own",
        "month-on-month": "Month-on-month",
        "year-on-year": "Year-on-year",
        "customers": "Customers",
        "VIP-customers": "VIP Customers",
        "monthly-sales": "Monthly sales",
        "annual-sales-rate": "Annual sales completion rate",
        "user-source": "User Source",
        "access-from": "Access From",
        "total-users": "Total Users",
        "new-users": "New Users",
        "active-users": "Active Users",
        "unique-visitors": "Unique Visitors",
        "visit": "Visit",
        "sign-up": "Sign-up",
        "conversion": "Conversion",
        "repeat-purchase": "Repeat Purchase",
        "search-engine": "Search Engine",
        "social-Media": "Social Media",
        "offline-channels": "Offline Channels",
        "content-community": "Content Community",
        "own-channels": "Own Channels",
        "advertising": "Advertising",
        "retain-users": "Retain Users",
        "returning-rate": "Returning Rate",
        "user-funnel": "User Funnel",
        "funnel": "Funnel",
        "error": "Error",
        "403-title": "Access to this page is restricted.",
        "403-subtitle": "Please check with the site admin if you believe this is a mistake.",
        "close-tab": "Close this tab",
        "404-title": "Sorry, we couldn't find this page.",
        "404-subtitle": "But dont worry, you can find plenty of other things on our homepage.",
        "title": "Title",
        "content": "Content",
        "create-at": "CreateAt",
        "system-name-is-required": "The system name is required.",
        "logo-is-required": "Logo is required.",
        "version-is-required": "Version is required.",
        "language-is-required": "Language is required.",
        "server-timeZone-is-required": "Server timeZone is required.",
        "image-min-size": "The image size cannot be less than 0",
        "sys-set": "System Information Settings",
        "version": "Version",
        "enter-version": "Enter version",
        "general-settings": "General Settings",
        "default-language": "Default language",
        "select-default-language": "Select Default language",
        "server-time-zone": "Server Time Zone",
        "select-time-zone": "Select timezone",
        "images-max-size": "Maximum size of uploaded images (kb)",
        "enter-images-max-size": "Enter maximum size of uploaded images",
        "security-settings": "Security Settings",
        "token-expiration": "Token Expiration Time (minute)",
        "enter-token-expiration": "Enter token Expiration Time",
        "token-expiration-tip": "If it never expires, fill in 0",
        "IP-whitelist": "IP Whitelist",
        "enter-IP-whitelist": "Enter IP whitelist",
        "IP-whitelist-tip": "Separate with commas. Leave blank to allow all IPs.",
        "silver": "Silver",
        "gold": "Gold",
        "diamond": "Diamond",
        "level-is-required": "Level is required",
        "expiration-is-required": "Expiration is required",
        "offline": "Offline",
        "select-all": "Select all",
        "select-row": "Select row",
        "user": "User",
        "level": "Level",
        "expiration-date": "Expiration Date",
        "effective": "Effective",
        "remark": "Remark",
        "status": "Status",
        "online": "Online",
        "user-level": "User Level",
        "export-excel": "Export Excel",
        "add-user": "Add User",
        "select-level": "Select User Level",
        "enter-remark": "Enter Remark",
        "passwords-confirm": "The two passwords you entered do not match.",
        "google-code-format": "The verification code must be 6 digits",
        "profile": "Profile",
        "google-auth": "Google Authenticator",
        "logout": "Logout",
        "new-password": "New Password",
        "re-enter-new-password": "Re-enter New Password",
        "update-password": "Update Password",
        "verification-code": "Verification Code",
        "google-auth-bounded": "Google Authenticator has been bound.",
        "rebinding": "Rebinding",
        "cancel-google-auth": "Cancel Google Authentication",
        "view-all-notification": "View All Notification",
        "no-results": "No results.",
        "total": "Total",
        "rows": "row(s)",
        "page-rows": "Rows per page",
        "page": "Page",
        "of": "of",
        "to-first-page": "Go to first page",
        "to-previous-page": "Go to previous page",
        "to-next-page": "Go to next page",
        "to-last-page": "Go to last page",
        "confirm-del": "Confirm deletion",
        "confirm-del-tip": "This operation cannot be undone. Do you want to confirm the deletion?",
        "preview": "Preview",
        "confirm": "Confirm",
        "no-country": "No country code found.",
        "search-country-code": "Search country code...",
        "enter-tele": "Enter tele",
        "select-date": "Select date",
        "examples": "Examples",
        "dashboard": "Dashboard",
        "user-analysis": "User Analysis",
        "sales-analysis": "Sales Analysis",
        "table": "Table",
        "pages": "Pages",
        "list": "List",
        "roles": "Roles",
        "role-switching": "Role Switching",
        "setting": "Setting",
        "error-page": "Error Page",
        "notice": "Notice",
        "admin-list": "Admin List",
        "admin-roles": "Admin Roles",
        "successful": "Successful",
        "name-exists": "Name already exists",
        "error-username-password": "Invalid username or password.",
        "incorrect-password": "Incorrect password",
        "user-not-exist": "User does not exist.",
        "google-no-bound": "No validator is bound.",
        "query-not-found": "Query not found.",
        "query-permission": "No permission to execute this query.",
        "query-error": "Query execution error.",
        "invalid-API": "Invalid API route.",
        "not-auth": "Not authenticated.",
        "token-error": "Token error.",
        "request-permission": "No permission for this request.",
        "API-not-found": "API function not found.",
        "command-search": "Type a command or search...",
        "search": "Search...",
        "browser-default": "Browser default",
        "403": "403",
        "404": "404",
        "up": "Up",
        "down": "Down",
        "this": "this",
        "month": "month",
        "day": "day",
        "compress-image": "Compressed images",
        "error-google-CAPTCHA": "Google verification failed"
    },
    zh: {
        "username-is-required": "用户名为必填项",
        "username-format": "只能包含数字和大小写字母",
        "password-min-length": "密码必须至少包含 6 个字符",
        "form-validation": "表单验证失败",
        "login-title": "登录您的账户",
        "login-subtitle": "请在下方输入您的用户名以登录您的账户",
        "username": "用户名",
        "username-enter": "输入您的用户名",
        "password": "密码",
        "login": "登录",
        "google-CAPTCHA": "谷歌验证码",
        "google-CAPTCHA-enter": "未绑定，无需填写",
        "name-is-required": "姓名为必填项",
        "select-area-code": "请选择区号",
        "enter-phone-number": "请输入您的电话号码",
        "select-min": "您必须至少选择一项。",
        "fail": "失败",
        "update": "更新",
        "delete": "删除",
        "query": "查询",
        "add-new": "添加",
        "admin": "管理员",
        "email": "邮箱",
        "tele": "电话",
        "address": "地址",
        "actions": "操作",
        "avatar": "头像",
        "name": "名称",
        "enter-name": "输入名称",
        "enter-email": "输入邮箱",
        "enter-address": "输入地址",
        "no-modify": "无需修改",
        "role-list": "角色列表",
        "save": "保存",
        "cancel": "取消",
        "verify-email": "请输入有效的电子邮件地址",
        "submit": "提交",
        "switch-role-title": "点击按钮切换角色。",
        "current-role": "当前角色",
        "super-admin": "超级管理员",
        "administrator": "管理员",
        "super-admin-tip": "超级管理员功能...",
        "permission-list": "权限列表",
        "edit-role": "编辑角色",
        "satisfied": "满意",
        "neutral": "中立",
        "dissatisfied": "不满意",
        "customer-satisfaction": "客户满意度",
        "customer-satisfaction-analysis": "客户满意度分析",
        "product-quality": "产品质量",
        "serve": "服务",
        "logistics": "物流",
        "after-sales": "售后",
        "recommend": "推荐",
        "score": "评分",
        "market-share": "市场份额",
        "sales-revenue": "销售收入",
        "order-count": "订单数量",
        "customer-count": "客户数量",
        "average-order-value": "平均订单金额",
        "competitor": "竞争对手",
        "own": "自有",
        "month-on-month": "环比",
        "year-on-year": "同比",
        "customers": "客户",
        "VIP-customers": "VIP客户",
        "monthly-sales": "月度销售额",
        "annual-sales-rate": "年度销售完成率",
        "user-source": "用户来源",
        "access-from": "访问来源",
        "total-users": "用户总数",
        "new-users": "新用户",
        "active-users": "活跃用户",
        "unique-visitors": "独立访客",
        "visit": "访问",
        "sign-up": "注册",
        "conversion": "转化",
        "repeat-purchase": "复购",
        "search-engine": "搜索引擎",
        "social-Media": "社交媒体",
        "offline-channels": "线下渠道",
        "content-community": "内容社区",
        "own-channels": "自有渠道",
        "advertising": "广告投放",
        "retain-users": "用户留存",
        "returning-rate": "回访率",
        "user-funnel": "用户转化漏斗",
        "funnel": "漏斗",
        "error": "错误",
        "403-title": "无权访问此页面",
        "403-subtitle": "如果您认为这是一个错误，请联系网站管理员。",
        "close-tab": "关闭此标签页",
        "404-title": "抱歉，未找到该页面。",
        "404-subtitle": "但别担心，您可以在主页上找到更多内容。",
        "title": "标题",
        "content": "内容",
        "create-at": "创建时间",
        "system-name-is-required": "系统名称为必填项。",
        "logo-is-required": "Logo 为必填项。",
        "version-is-required": "版本号为必填项。",
        "language-is-required": "语言为必填项。",
        "server-timeZone-is-required": "服务器时区为必填项。",
        "image-min-size": "图片大小不能小于 0。",
        "sys-set": "系统信息设置",
        "version": "版本",
        "enter-version": "请输入版本号",
        "general-settings": "通用设置",
        "default-language": "默认语言",
        "select-default-language": "选择默认语言",
        "server-time-zone": "服务器时区",
        "select-time-zone": "选择时区",
        "images-max-size": "上传图片的最大大小(KB)",
        "enter-images-max-size": "请输入上传图片的最大大小",
        "security-settings": "安全设置",
        "token-expiration": "Token 过期时间（分钟）",
        "enter-token-expiration": "请输入 Token 过期时间",
        "token-expiration-tip": "若永不过期，请填写 0",
        "IP-whitelist": "IP 白名单",
        "enter-IP-whitelist": "请输入 IP 白名单",
        "IP-whitelist-tip": "逗号分隔。留空表示允许所有 IP。",
        "silver": "白银",
        "gold": "黄金",
        "diamond": "钻石",
        "level-is-required": "等级为必填项。",
        "expiration-is-required": "到期时间为必填项。",
        "offline": "离线",
        "select-all": "全选",
        "select-row": "选择行",
        "user": "用户",
        "level": "等级",
        "expiration-date": "到期日期",
        "effective": "生效",
        "remark": "备注",
        "status": "状态",
        "online": "在线",
        "user-level": "用户等级",
        "export-excel": "导出 Excel",
        "add-user": "添加用户",
        "select-level": "选择用户等级",
        "enter-remark": "输入备注",
        "passwords-confirm": "两次输入的密码不一致。",
        "google-code-format": "验证码必须是 6 位数字。",
        "profile": "个人资料",
        "google-auth": "谷歌验证器",
        "logout": "退出登录",
        "new-password": "新密码",
        "re-enter-new-password": "再次输入新密码",
        "update-password": "更新密码",
        "verification-code": "验证码",
        "google-auth-bounded": "谷歌验证器已绑定。",
        "rebinding": "重新绑定",
        "cancel-google-auth": "取消谷歌验证",
        "view-all-notification": "查看全部通知",
        "no-results": "暂无结果。",
        "total": "总计",
        "rows": "行",
        "page-rows": "每页行数",
        "page": "页",
        "of": "共",
        "to-first-page": "跳至第一页",
        "to-previous-page": "上一页",
        "to-next-page": "下一页",
        "to-last-page": "跳至最后一页",
        "confirm-del": "确认删除",
        "confirm-del-tip": "此操作无法撤销，是否确认删除？",
        "preview": "预览",
        "confirm": "确认",
        "no-country": "未找到国家代码。",
        "search-country-code": "搜索国家代码...",
        "enter-tele": "输入电话号码",
        "select-date": "选择日期",
        "examples": "示例",
        "dashboard": "仪表盘",
        "user-analysis": "用户分析",
        "sales-analysis": "销售分析",
        "table": "表格",
        "pages": "页面",
        "list": "列表",
        "roles": "角色",
        "role-switching": "角色切换",
        "setting": "设置",
        "error-page": "错误页面",
        "notice": "通知",
        "admin-list": "管理员列表",
        "admin-roles": "管理员角色",
        "successful": "操作成功",
        "name-exists": "名称已存在",
        "error-username-password": "用户名或密码错误。",
        "incorrect-password": "密码不正确。",
        "user-not-exist": "用户不存在。",
        "google-no-bound": "未绑定验证器。",
        "query-not-found": "未找到查询。",
        "query-permission": "无权执行该查询。",
        "query-error": "查询执行出错。",
        "invalid-API": "无效的 API 路由。",
        "not-auth": "未登录或未认证。",
        "token-error": "Token 错误。",
        "request-permission": "无权访问该请求。",
        "API-not-found": "未找到对应的 API 接口。",
        "command-search": "输入命令或搜索...",
        "search": "搜索...",
        "browser-default": "浏览器默认",
        "403": "403",
        "404": "404",
        "up": "上升",
        "down": "下降",
        "this": "本",
        "month": "月",
        "day": "日",
        "compress-image": "压缩图片",
        "error-google-CAPTCHA": "谷歌验证失败"
    },
    es: {
        "username-is-required": "El nombre de usuario es obligatorio",
        "username-format": "Solo puede contener números, mayúsculas y minúsculas",
        "password-min-length": "La contraseña debe tener al menos 6 caracteres",
        "form-validation": "Error en la validación del formulario",
        "login-title": "Inicia sesión en tu cuenta",
        "login-subtitle": "Introduce tu nombre de usuario a continuación para iniciar sesión en tu cuenta",
        "username": "Nombre de usuario",
        "username-enter": "Introduce tu nombre de usuario",
        "password": "Contraseña",
        "login": "Iniciar sesión",
        "google-CAPTCHA": "Captcha de Google",
        "google-CAPTCHA-enter": "No vinculado, no rellenar",
        "name-is-required": "Nombre obligatorio",
        "select-area-code": "Seleccione el código de área",
        "enter-phone-number": "Introduzca su número de teléfono",
        "select-min": "Debe seleccionar al menos un elemento",
        "fail": "Error",
        "update": "Actualizar",
        "delete": "Eliminar",
        "query": "Consulta",
        "add-new": "Añadir nuevo",
        "admin": "Administrador",
        "email": "Correo electrónico",
        "tele": "Tele",
        "address": "Dirección",
        "actions": "Acciones",
        "avatar": "Avatar",
        "name": "Nombre",
        "enter-name": "Introduzca el nombre",
        "enter-email": "Introduzca el correo electrónico",
        "enter-address": "Introduzca la dirección",
        "no-modify": "No es necesario modificar",
        "role-list": "Lista de roles",
        "save": "Guardar",
        "cancel": "Cancelar",
        "verify-email": "Por favor, introduce una dirección de correo electrónico válida",
        "submit": "Enviar",
        "switch-role-title": "Haz clic en el botón para cambiar de rol.",
        "current-role": "Rol actual",
        "super-admin": "Superadministrador",
        "administrator": "Administrador",
        "super-admin-tip": "Función de superadministrador...",
        "permission-list": "Lista de permisos",
        "edit-role": "Editar rol",
        "satisfied": "Satisfecho",
        "neutral": "Neutral",
        "dissatisfied": "Insatisfecho",
        "customer-satisfaction": "Satisfacción del cliente",
        "customer-satisfaction-analysis": "Análisis de satisfacción del cliente",
        "product-quality": "Calidad del producto",
        "serve": "Servicio",
        "logistics": "Logística",
        "after-sales": "Postventa",
        "recommend": "Recomendar",
        "score": "Puntuación",
        "market-share": "Cuota de mercado",
        "sales-revenue": "Ingresos por ventas",
        "order-count": "Cantidad de pedidos",
        "customer-count": "Número de clientes",
        "average-order-value": "Valor medio del pedido",
        "competitor": "Competidor",
        "own": "Propio",
        "month-on-month": "Mes a mes",
        "year-on-year": "Año tras año",
        "customers": "Clientes",
        "VIP-customers": "Clientes VIP",
        "monthly-sales": "Ventas mensuales",
        "annual-sales-rate": "Tasa de finalización de ventas anuales",
        "user-source": "Fuente de usuarios",
        "access-from": "Acceso desde",
        "total-users": "Usuarios totales",
        "new-users": "Nuevos usuarios",
        "active-users": "Usuarios activos",
        "unique-visitors": "Visitantes únicos",
        "visit": "Visita",
        "sign-up": "Registro",
        "conversion": "Conversión",
        "repeat-purchase": "Compra repetida",
        "search-engine": "Motor de búsqueda",
        "social-Media": "Redes sociales",
        "offline-channels": "Canales offline",
        "content-community": "Comunidad de contenido",
        "own-channels": "Canales propios",
        "advertising": "Publicidad",
        "retain-users": "Retener usuarios",
        "returning-rate": "Tasa de retorno",
        "user-funnel": "Embudo de usuarios",
        "funnel": "Embudo",
        "error": "Error",
        "403-title": "El acceso a esta página está restringido.",
        "403-subtitle": "Por favor, contacta con el administrador del sitio si crees que es un error.",
        "close-tab": "Cerrar esta pestaña",
        "404-title": "Lo sentimos, no pudimos encontrar esta página.",
        "404-subtitle": "Pero no te preocupes, puedes encontrar muchas otras cosas en nuestra página principal.",
        "title": "Título",
        "content": "Contenido",
        "create-at": "Creado en",
        "system-name-is-required": "El nombre del sistema es obligatorio.",
        "logo-is-required": "El logotipo es obligatorio.",
        "version-is-required": "La versión es obligatoria.",
        "language-is-required": "El idioma es obligatorio.",
        "server-timeZone-is-required": "La zona horaria del servidor es obligatoria.",
        "image-min-size": "El tamaño de la imagen no puede ser menor que 0",
        "sys-set": "Configuración de información del sistema",
        "version": "Versión",
        "enter-version": "Introduce la versión",
        "general-settings": "Configuraciones generales",
        "default-language": "Idioma predeterminado",
        "select-default-language": "Selecciona el idioma predeterminado",
        "server-time-zone": "Zona horaria del servidor",
        "select-time-zone": "Selecciona la zona horaria",
        "images-max-size": "Tamaño máximo de las imágenes subidas (kb)",
        "enter-images-max-size": "Introduce el tamaño máximo de las imágenes subidas",
        "security-settings": "Configuraciones de seguridad",
        "token-expiration": "Tiempo de expiración del token (minutos)",
        "enter-token-expiration": "Introduce el tiempo de expiración del token",
        "token-expiration-tip": "Si nunca expira, escribe 0",
        "IP-whitelist": "Lista blanca de IP",
        "enter-IP-whitelist": "Introduce la lista blanca de IP",
        "IP-whitelist-tip": "Separar con comas. Déjalo en blanco para permitir todas las IP.",
        "silver": "Plata",
        "gold": "Oro",
        "diamond": "Diamante",
        "level-is-required": "El nivel es obligatorio",
        "expiration-is-required": "La fecha de expiración es obligatoria",
        "offline": "Desconectado",
        "select-all": "Seleccionar todo",
        "select-row": "Seleccionar fila",
        "user": "Usuario",
        "level": "Nivel",
        "expiration-date": "Fecha de expiración",
        "effective": "Efectivo",
        "remark": "Observación",
        "status": "Estado",
        "online": "En línea",
        "user-level": "Nivel de usuario",
        "export-excel": "Exportar a Excel",
        "add-user": "Agregar usuario",
        "select-level": "Seleccionar nivel de usuario",
        "enter-remark": "Introducir observación",
        "passwords-confirm": "Las dos contraseñas introducidas no coinciden.",
        "google-code-format": "El código de verificación debe tener 6 dígitos",
        "profile": "Perfil",
        "google-auth": "Autenticador de Google",
        "logout": "Cerrar sesión",
        "new-password": "Nueva contraseña",
        "re-enter-new-password": "Reingresa la nueva contraseña",
        "update-password": "Actualizar contraseña",
        "verification-code": "Código de verificación",
        "google-auth-bounded": "El autenticador de Google ya está vinculado.",
        "rebinding": "Volver a vincular",
        "cancel-google-auth": "Cancelar autenticación de Google",
        "view-all-notification": "Ver todas las notificaciones",
        "no-results": "Sin resultados.",
        "total": "Total",
        "rows": "fila(s)",
        "page-rows": "Filas por página",
        "page": "Página",
        "of": "de",
        "to-first-page": "Ir a la primera página",
        "to-previous-page": "Ir a la página anterior",
        "to-next-page": "Ir a la página siguiente",
        "to-last-page": "Ir a la última página",
        "confirm-del": "Confirmar eliminación",
        "confirm-del-tip": "Esta acción no se puede deshacer. ¿Deseas confirmar la eliminación?",
        "preview": "Vista previa",
        "confirm": "Confirmar",
        "no-country": "No se encontró código de país.",
        "search-country-code": "Buscar código de país...",
        "enter-tele": "Introduce teléfono",
        "select-date": "Seleccionar fecha",
        "examples": "Ejemplos",
        "dashboard": "Panel de control",
        "user-analysis": "Análisis de usuarios",
        "sales-analysis": "Análisis de ventas",
        "table": "Tabla",
        "pages": "Páginas",
        "list": "Lista",
        "roles": "Roles",
        "role-switching": "Cambio de rol",
        "setting": "Configuración",
        "error-page": "Página de error",
        "notice": "Aviso",
        "admin-list": "Lista de administradores",
        "admin-roles": "Roles de administrador",
        "successful": "Exitoso",
        "name-exists": "El nombre ya existe",
        "error-username-password": "Nombre de usuario o contraseña no válidos.",
        "incorrect-password": "Contraseña incorrecta",
        "user-not-exist": "El usuario no existe.",
        "google-no-bound": "No hay validador vinculado.",
        "query-not-found": "Consulta no encontrada.",
        "query-permission": "Sin permiso para ejecutar esta consulta.",
        "query-error": "Error en la ejecución de la consulta.",
        "invalid-API": "Ruta de API no válida.",
        "not-auth": "No autenticado.",
        "token-error": "Error de token.",
        "request-permission": "Sin permiso para esta solicitud.",
        "API-not-found": "Función de API no encontrada.",
        "command-search": "Escribe un comando o busca...",
        "search": "Buscar...",
        "browser-default": "Predeterminado del navegador",
        "403": "403",
        "404": "404",
        "up": "Subir",
        "down": "Bajar",
        "this": "este",
        "month": "mes",
        "day": "día",
        "compress-image": "Imágenes comprimidas",
        "error-google-CAPTCHA": "Falló la verificación de Google."
    },
    fr: {
        "username-is-required": "Nom d'utilisateur requis",
        "username-format": "Ne peut contenir que des chiffres, des majuscules et des minuscules",
        "password-min-length": "Le mot de passe doit comporter au moins 6 caractères",
        "form-validation": "La validation du formulaire a échoué",
        "login-title": "Connectez-vous à votre compte",
        "login-subtitle": "Saisissez votre nom d'utilisateur ci-dessous pour vous connecter à votre compte",
        "username": "Nom d'utilisateur",
        "username-enter": "Saisissez votre nom d'utilisateur",
        "password": "Mot de passe",
        "login": "Connexion",
        "google-CAPTCHA": "Captcha Google",
        "google-CAPTCHA-enter": "Non lié, ne pas remplir",
        "name-is-required": "Nom requis",
        "select-area-code": "Veuillez sélectionner l'indicatif régional",
        "enter-phone-number": "Veuillez saisir votre numéro de téléphone",
        "select-min": "Vous devez sélectionner au moins un élément.",
        "fail": "Échec",
        "update": "Mettre à jour",
        "delete": "Supprimer",
        "query": "Requête",
        "add-new": "Ajouter un nouveau",
        "admin": "Administrateur",
        "email": "E-mail",
        "tele": "Téléphone",
        "address": "Adresse",
        "actions": "Actions",
        "avatar": "Avatar",
        "name": "Nom",
        "enter-name": "Saisir le nom",
        "enter-email": "Saisir l'e-mail",
        "enter-address": "Saisir adresse",
        "no-modify": "Aucune modification nécessaire",
        "role-list": "Liste des rôles",
        "save": "Enregistrer",
        "cancel": "Annuler",
        "verify-email": "Veuillez entrer une adresse e-mail valide",
        "submit": "Soumettre",
        "switch-role-title": "Cliquez sur le bouton pour changer de rôle.",
        "current-role": "Rôle actuel",
        "super-admin": "Super administrateur",
        "administrator": "Administrateur",
        "super-admin-tip": "Fonction de super administrateur...",
        "permission-list": "Liste des permissions",
        "edit-role": "Modifier le rôle",
        "satisfied": "Satisfait",
        "neutral": "Neutre",
        "dissatisfied": "Insatisfait",
        "customer-satisfaction": "Satisfaction client",
        "customer-satisfaction-analysis": "Analyse de la satisfaction client",
        "product-quality": "Qualité du produit",
        "serve": "Service",
        "logistics": "Logistique",
        "after-sales": "Service après-vente",
        "recommend": "Recommander",
        "score": "Score",
        "market-share": "Part de marché",
        "sales-revenue": "Revenus des ventes",
        "order-count": "Nombre de commandes",
        "customer-count": "Nombre de clients",
        "average-order-value": "Valeur moyenne de commande",
        "competitor": "Concurrent",
        "own": "Propre",
        "month-on-month": "Mois sur mois",
        "year-on-year": "Année sur année",
        "customers": "Clients",
        "VIP-customers": "Clients VIP",
        "monthly-sales": "Ventes mensuelles",
        "annual-sales-rate": "Taux d’achèvement des ventes annuelles",
        "user-source": "Source des utilisateurs",
        "access-from": "Accès depuis",
        "total-users": "Utilisateurs totaux",
        "new-users": "Nouveaux utilisateurs",
        "active-users": "Utilisateurs actifs",
        "unique-visitors": "Visiteurs uniques",
        "visit": "Visite",
        "sign-up": "Inscription",
        "conversion": "Conversion",
        "repeat-purchase": "Achat répété",
        "search-engine": "Moteur de recherche",
        "social-Media": "Réseaux sociaux",
        "offline-channels": "Canaux hors ligne",
        "content-community": "Communauté de contenu",
        "own-channels": "Canaux propres",
        "advertising": "Publicité",
        "retain-users": "Conserver les utilisateurs",
        "returning-rate": "Taux de retour",
        "user-funnel": "Entonnoir utilisateur",
        "funnel": "Entonnoir",
        "error": "Erreur",
        "403-title": "L’accès à cette page est restreint.",
        "403-subtitle": "Veuillez contacter l’administrateur du site si vous pensez qu’il s’agit d’une erreur.",
        "close-tab": "Fermer cet onglet",
        "404-title": "Désolé, nous n’avons pas pu trouver cette page.",
        "404-subtitle": "Mais ne vous inquiétez pas, vous pouvez trouver beaucoup d’autres choses sur notre page d’accueil.",
        "title": "Titre",
        "content": "Contenu",
        "create-at": "Créé le",
        "system-name-is-required": "Le nom du système est requis.",
        "logo-is-required": "Le logo est requis.",
        "version-is-required": "La version est requise.",
        "language-is-required": "La langue est requise.",
        "server-timeZone-is-required": "Le fuseau horaire du serveur est requis.",
        "image-min-size": "La taille de l’image ne peut pas être inférieure à 0",
        "sys-set": "Paramètres des informations système",
        "version": "Version",
        "enter-version": "Entrer la version",
        "general-settings": "Paramètres généraux",
        "default-language": "Langue par défaut",
        "select-default-language": "Sélectionner la langue par défaut",
        "server-time-zone": "Fuseau horaire du serveur",
        "select-time-zone": "Sélectionner le fuseau horaire",
        "images-max-size": "Taille maximale des images téléchargées (ko)",
        "enter-images-max-size": "Entrer la taille maximale des images téléchargées",
        "security-settings": "Paramètres de sécurité",
        "token-expiration": "Durée d’expiration du jeton (minute)",
        "enter-token-expiration": "Entrer la durée d’expiration du jeton",
        "token-expiration-tip": "S’il n’expire jamais, indiquez 0",
        "IP-whitelist": "Liste blanche IP",
        "enter-IP-whitelist": "Entrer la liste blanche IP",
        "IP-whitelist-tip": "Séparez par des virgules. Laissez vide pour autoriser toutes les IP.",
        "silver": "Argent",
        "gold": "Or",
        "diamond": "Diamant",
        "level-is-required": "Le niveau est requis",
        "expiration-is-required": "La date d’expiration est requise",
        "offline": "Hors ligne",
        "select-all": "Tout sélectionner",
        "select-row": "Sélectionner la ligne",
        "user": "Utilisateur",
        "level": "Niveau",
        "expiration-date": "Date d’expiration",
        "effective": "Effectif",
        "remark": "Remarque",
        "status": "Statut",
        "online": "En ligne",
        "user-level": "Niveau d’utilisateur",
        "export-excel": "Exporter vers Excel",
        "add-user": "Ajouter un utilisateur",
        "select-level": "Sélectionner le niveau d’utilisateur",
        "enter-remark": "Entrer une remarque",
        "passwords-confirm": "Les deux mots de passe saisis ne correspondent pas.",
        "google-code-format": "Le code de vérification doit comporter 6 chiffres",
        "profile": "Profil",
        "google-auth": "Google Authenticator",
        "logout": "Se déconnecter",
        "new-password": "Nouveau mot de passe",
        "re-enter-new-password": "Ressaisir le nouveau mot de passe",
        "update-password": "Mettre à jour le mot de passe",
        "verification-code": "Code de vérification",
        "google-auth-bounded": "Google Authenticator est déjà lié.",
        "rebinding": "Relier à nouveau",
        "cancel-google-auth": "Annuler l’authentification Google",
        "view-all-notification": "Voir toutes les notifications",
        "no-results": "Aucun résultat.",
        "total": "Total",
        "rows": "ligne(s)",
        "page-rows": "Lignes par page",
        "page": "Page",
        "of": "de",
        "to-first-page": "Aller à la première page",
        "to-previous-page": "Aller à la page précédente",
        "to-next-page": "Aller à la page suivante",
        "to-last-page": "Aller à la dernière page",
        "confirm-del": "Confirmer la suppression",
        "confirm-del-tip": "Cette opération est irréversible. Voulez-vous vraiment confirmer la suppression ?",
        "preview": "Aperçu",
        "confirm": "Confirmer",
        "no-country": "Aucun code de pays trouvé.",
        "search-country-code": "Rechercher un code de pays...",
        "enter-tele": "Entrer un téléphone",
        "select-date": "Sélectionner une date",
        "examples": "Exemples",
        "dashboard": "Tableau de bord",
        "user-analysis": "Analyse des utilisateurs",
        "sales-analysis": "Analyse des ventes",
        "table": "Tableau",
        "pages": "Pages",
        "list": "Liste",
        "roles": "Rôles",
        "role-switching": "Changement de rôle",
        "setting": "Paramètre",
        "error-page": "Page d’erreur",
        "notice": "Avis",
        "admin-list": "Liste des administrateurs",
        "admin-roles": "Rôles d’administrateur",
        "successful": "Réussi",
        "name-exists": "Le nom existe déjà",
        "error-username-password": "Nom d’utilisateur ou mot de passe invalide.",
        "incorrect-password": "Mot de passe incorrect",
        "user-not-exist": "L’utilisateur n’existe pas.",
        "google-no-bound": "Aucun validateur lié.",
        "query-not-found": "Requête introuvable.",
        "query-permission": "Aucune autorisation pour exécuter cette requête.",
        "query-error": "Erreur lors de l’exécution de la requête.",
        "invalid-API": "Route d’API invalide.",
        "not-auth": "Non authentifié.",
        "token-error": "Erreur de jeton.",
        "request-permission": "Aucune autorisation pour cette demande.",
        "API-not-found": "Fonction API introuvable.",
        "command-search": "Tapez une commande ou recherchez...",
        "search": "Rechercher...",
        "browser-default": "Par défaut du navigateur",
        "403": "403",
        "404": "404",
        "up": "En hausse",
        "down": "En baisse",
        "this": "ce",
        "month": "mois",
        "day": "jour",
        "compress-image": "Images compressées",
        "error-google-CAPTCHA": "La vérification Google a échoué"
    }
} as const;

export type LanguageKey = keyof typeof languages;