"use client";

export interface PhoneCode {
    code: string;
    country: string;
    label: string;
}

export const phoneCodes: PhoneCode[] = [
    { code: "+1", country: "United States / Canada", label: "🇺🇸 United States / 🇨🇦 Canada (+1)" },
    { code: "+7", country: "Russia / Kazakhstan", label: "🇷🇺 Russia (+7)" },
    { code: "+20", country: "Egypt", label: "🇪🇬 Egypt (+20)" },
    { code: "+27", country: "South Africa", label: "🇿🇦 South Africa (+27)" },
    { code: "+30", country: "Greece", label: "🇬🇷 Greece (+30)" },
    { code: "+31", country: "Netherlands", label: "🇳🇱 Netherlands (+31)" },
    { code: "+32", country: "Belgium", label: "🇧🇪 Belgium (+32)" },
    { code: "+33", country: "France", label: "🇫🇷 France (+33)" },
    { code: "+34", country: "Spain", label: "🇪🇸 Spain (+34)" },
    { code: "+39", country: "Italy", label: "🇮🇹 Italy (+39)" },
    { code: "+44", country: "United Kingdom", label: "🇬🇧 United Kingdom (+44)" },
    { code: "+49", country: "Germany", label: "🇩🇪 Germany (+49)" },
    { code: "+52", country: "Mexico", label: "🇲🇽 Mexico (+52)" },
    { code: "+55", country: "Brazil", label: "🇧🇷 Brazil (+55)" },
    { code: "+60", country: "Malaysia", label: "🇲🇾 Malaysia (+60)" },
    { code: "+61", country: "Australia", label: "🇦🇺 Australia (+61)" },
    { code: "+62", country: "Indonesia", label: "🇮🇩 Indonesia (+62)" },
    { code: "+63", country: "Philippines", label: "🇵🇭 Philippines (+63)" },
    { code: "+65", country: "Singapore", label: "🇸🇬 Singapore (+65)" },
    { code: "+66", country: "Thailand", label: "🇹🇭 Thailand (+66)" },
    { code: "+81", country: "Japan", label: "🇯🇵 Japan (+81)" },
    { code: "+82", country: "South Korea", label: "🇰🇷 South Korea (+82)" },
    { code: "+84", country: "Vietnam", label: "🇻🇳 Vietnam (+84)" },
    { code: "+86", country: "China", label: "🇨🇳 China (+86)" },
    { code: "+852", country: "Hong Kong", label: "🇭🇰 Hong Kong (+852)" },
    { code: "+853", country: "Macau", label: "🇲🇴 Macau (+853)" },
    { code: "+886", country: "Taiwan", label: "🇹🇼 Taiwan (+886)" },
    { code: "+91", country: "India", label: "🇮🇳 India (+91)" },
    { code: "+92", country: "Pakistan", label: "🇵🇰 Pakistan (+92)" },
    { code: "+94", country: "Sri Lanka", label: "🇱🇰 Sri Lanka (+94)" },
    { code: "+98", country: "Iran", label: "🇮🇷 Iran (+98)" },
    { code: "+212", country: "Morocco", label: "🇲🇦 Morocco (+212)" },
    { code: "+254", country: "Kenya", label: "🇰🇪 Kenya (+254)" },
    { code: "+353", country: "Ireland", label: "🇮🇪 Ireland (+353)" },
    { code: "+354", country: "Iceland", label: "🇮🇸 Iceland (+354)" },
    { code: "+358", country: "Finland", label: "🇫🇮 Finland (+358)" },
    { code: "+380", country: "Ukraine", label: "🇺🇦 Ukraine (+380)" },
    { code: "+852", country: "Hong Kong", label: "🇭🇰 Hong Kong (+852)" },
    { code: "+972", country: "Israel", label: "🇮🇱 Israel (+972)" },
    { code: "+965", country: "Kuwait", label: "🇰🇼 Kuwait (+965)" },
    { code: "+971", country: "United Arab Emirates", label: "🇦🇪 United Arab Emirates (+971)" },
    { code: "+972", country: "Israel", label: "🇮🇱 Israel (+972)" },
    { code: "+994", country: "Azerbaijan", label: "🇦🇿 Azerbaijan (+994)" },
    { code: "+995", country: "Georgia", label: "🇬🇪 Georgia (+995)" },
    { code: "+998", country: "Uzbekistan", label: "🇺🇿 Uzbekistan (+998)" },
] as const